### ISSUE TITLE
WUT is not working properly somtimes after trying pressing shift+left button to send items to AE network

### ISSUE THREAD

**Issue by l741589** [p455w0rd/AE2WirelessTerminalLibrary#9]
WUT is not working properly somtimes after trying pressing shift+left button to send items to AE network。
and then reopen the UWT again, WFT，WCT，WPT dislay nothing, only WIT works right.

vesion
```
AE2:rv6-stable-7
AE2WTLib:1.0.3.4
WCT:3.12.97
WFT:1.0.4
WIT:1.0.2
WPT:1.0.3
p455w0rd's lib:2.3.161
```

stack
```
java.util.concurrent.ExecutionException: java.lang.ClassCastException: appeng.util.item.AEItemStack cannot be cast to appeng.api.storage.data.IAEFluidStack
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_211]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_211]
	at net.minecraft.util.Util.func_181617_a(Util.java:48) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
Caused by: java.lang.ClassCastException: appeng.util.item.AEItemStack cannot be cast to appeng.api.storage.data.IAEFluidStack
	at appeng.me.storage.MEMonitorIFluidHandler.canAccept(MEMonitorIFluidHandler.java:48) ~[MEMonitorIFluidHandler.class:?]
	at appeng.me.storage.MEInventoryHandler.canAccept(MEInventoryHandler.java:167) ~[MEInventoryHandler.class:?]
	at appeng.me.storage.NetworkInventoryHandler.injectItems(NetworkInventoryHandler.java:99) ~[NetworkInventoryHandler.class:?]
	at appeng.me.cache.NetworkMonitor.injectItems(NetworkMonitor.java:157) ~[NetworkMonitor.class:?]
	at p455w0rd.ae2wtlib.helpers.WTGuiObjectImpl.injectItems(WTGuiObjectImpl.java:203) ~[WTGuiObjectImpl.class:?]
	at appeng.util.Platform.poweredInsert(Platform.java:1229) ~[Platform.class:?]
	at appeng.util.Platform.poweredInsert(Platform.java:1218) ~[Platform.class:?]
	at p455w0rd.wct.container.ContainerWCT.shiftStoreItem(ContainerWCT.java:1143) ~[ContainerWCT.class:?]
	at p455w0rd.wct.container.ContainerWCT.func_82846_b(ContainerWCT.java:989) ~[ContainerWCT.class:?]
	at net.minecraft.inventory.Container.func_184996_a(Container.java:246) ~[afr.class:?]
	at p455w0rd.wct.container.ContainerWCT.func_184996_a(ContainerWCT.java:1154) ~[ContainerWCT.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1162) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:20) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_211]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_211]
	at net.minecraft.util.Util.func_181617_a(Util.java:47) ~[h.class:?]
	... 5 more
```

**Comment by TheInfamousAlk** [comment]
Also having this issue.

**Comment by ChromaPIE** [comment]
Same

**Comment by UnderMan4** [comment]
Same

**Comment by TrapStoner** [comment]
Same in 1.12.2 in 2021 wtf??

**Comment by Blank-1973** [comment]
Is there any chance that this problem will be fixed?

**Comment by TrapStoner** [comment]
i don't think so... just dont try to shove items with shift into the wrong terminal
